-- Opdater eksisterende portal-import (firmanavne m.m.)
--
-- 1. På portalservren (UTF-8 bevares):
--    php ~/generate_portal_import_sql.php --installers-only --output=portal_migration_update_installers.sql
--
--    Eller firma + brugere (uden audit_logs):
--    php ~/generate_portal_import_sql.php --output=portal_migration_update.sql
--
-- 2. Kør den genererede fil mod ABAS:
--    mysql ... abas < portal_migration_update_installers.sql
--
-- Scriptet opdaterer approved_installers.company_name via ON DUPLICATE KEY UPDATE,
-- erstatter import-*.trekantbrand-import.local med rigtige domæner hvor muligt,
-- og opdaterer brugernes display-navne.
