-- Opdater eksisterende portal-import (firmanavne m.m.)
--
-- Fil klar til brug: Database/imports/portal_migration_update.sql
-- (genereret fra portalservren med korrekt UTF-8)
--
-- Gen-generer ved behov (fra projektroden, kræver VPN + PuTTY):
--   .\scripts\fetch_portal_update_sql.ps1
--   .\scripts\fetch_portal_update_sql.ps1 -InstallersOnly
--
-- Kør mod ABAS efter backup:
--   mysql ... abas < Database/imports/portal_migration_update.sql
